#!/usr/bin/env ruby

# comma-ifies numbers
# in arbitrary text.  for example, "hadoop dfs -ls".
#
# TODO python 2.7 {,} format command obsoletes this. should switch.

def commify(n)
    # http://codesnippets.joyent.com/posts/show/330
    n.to_s =~ /([^\.]*)(\..*)?/
    int, dec = $1.reverse, $2 ? $2 : ""
    while int.gsub!(/(,|\.|^)(\d{3})(\d)/, '\1\2,\3')
    end
    int.reverse + dec
end

for line in STDIN
  s = line.gsub(/(^|\s)([0-9\.]+)(\s|^)/){ 
    lhs = $1
    strnum = $2
    rhs = $3
    lhs + commify(strnum) + rhs
    # strnum = $1
    # commify(strnum)
  }
  puts s
end


