#!/usr/bin/env python2.7
# http://philzimmermann.com/docs/human-oriented-base-32-encoding.txt
# https://pypi.python.org/pypi/zbase32/
import os,sys
import zbase32  # tested with version 1.1.5, pypi upload 2012-08-27

nbytes = 16 if len(sys.argv)<2 else int(sys.argv[1])
print zbase32.zbase32.b2a(os.urandom(nbytes))


